[package]
name = "kisel"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["pepzi"]
description = "Multi-system 8-bit emulator (Game Boy first)"
repository = "https://github.com/pepzi/kisel"
readme = "README.md"
keywords = ["emulator", "gameboy", "nes"]
categories = ["emulators"]

[dependencies]
minifb = "0.28"
rfd = "0.17"